apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: testapp-pod
  template:
    metadata:
      labels:
        app: testapp-pod
    spec:
      containers:
      - name: testapp-ctr
        image: kikeymeenan/testapp1
        ports:
        - name: testapp-ext
          containerPort: 3000
        env:
        - name: USER_SECRET
          valueFrom:
            secretKeyRef:
              name: mk-secret
              key: user
        - name: API_SERVICE
          value: testapp2-service.default.svc.cluster.local
