apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeaffinity-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodeaffinity-pod
  template:
    metadata:
      labels:
        app: nodeaffinity-pod
    spec:
      affinity:
        nodeAffinity:
          # requiredDuringSchedulingIgnoredDuringExecution:
          #   nodeSelectorTerms:
          #   - matchExpressions:
          #     - key: env
          #       operator: In
          #       values:
          #       - dev
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 3
            preference:
              matchExpressions:
                - key: team
                  operator: In
                  values:
                  - engineering-project1
          - weight: 1
            preference:
              matchExpressions:
                - key: env
                  operator: In
                  values:
                  - dev
      containers:
      - name: nodeaffinity-ctr
        image: kikeymeenan/testapp2
        imagePullPolicy: IfNotPresent
        ports:
        - name: nodeaffinity-ext
          containerPort: 3000
