apiVersion: apps/v1
kind: Deployment
metadata:
  name: podaffinity-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-affinity-1
  template:
    metadata:
      labels:
        app: pod-affinity-1
    spec:
      containers:
      - name: podaffinity-ctr
        image: kikeymeenan/testapp2
        imagePullPolicy: IfNotPresent
        ports:
        - name: podaffinity-ext
          containerPort: 3000