apiVersion: v1
kind: Service
metadata:
  name: testapp2-service
spec:
  ports:
  - port: 31002
    nodePort: 31002
    targetPort: testapp2-ext
    protocol: TCP
  selector:
    app: testapp2-pod
  type: NodePort
